export type PublicThemeKey =
  | "CLASICO"
  | "MERCADO"
  | "ELEGANTE"
  | "TAQUERIA"
  | "MARISQUERIA"
  | "CAFETERIA"
  | "PIZZERIA"
  | "SUSHI"
  | "HAMBURGUESAS"
  | "ANTOJITOS"
  | "BAR_BOTANERO"
  | "DARK_KITCHEN"
  | "POLLERIA";

export type PublicTheme = {
  label: string;
  description: string;
  page: string;
  header: string;
  eyebrow: string;
  title: string;
  body: string;
  socialLink: string;
  panel: string;
  productCard: string;
  cartItem: string;
  input: string;
  primaryBtn: string;
  secondaryBtn: string;
  titleText: string;
  bodyText: string;
  helperText: string;
  priceText: string;
  accentPill: string;
  customizer: string;
  customizerText: string;
};

export const publicThemes: Record<PublicThemeKey, PublicTheme> = {
  CLASICO: {
    label: "Clásico limpio",
    description: "Minimalista, claro y fácil de leer.",
    page: "bg-slate-100",
    header: "bg-white text-slate-950 ring-1 ring-slate-200",
    eyebrow: "text-slate-500",
    title: "text-slate-950",
    body: "text-slate-600",
    socialLink: "border-slate-300 bg-white text-slate-700 hover:bg-slate-50",
    panel: "border-slate-200 bg-white text-slate-950",
    productCard: "border-slate-200 bg-white text-slate-950 shadow-sm",
    cartItem: "border-slate-200 bg-slate-50 text-slate-900",
    input: "border-slate-300 bg-white text-slate-950 placeholder:text-slate-400",
    primaryBtn: "bg-slate-950 text-white hover:bg-slate-800",
    secondaryBtn: "border-slate-300 bg-white text-slate-700 hover:bg-slate-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-600",
    helperText: "text-slate-500",
    priceText: "text-emerald-700",
    accentPill: "bg-emerald-50 text-emerald-800",
    customizer: "border-slate-200 bg-white",
    customizerText: "text-slate-800",
  },
  MERCADO: {
    label: "Mercado mexicano",
    description: "Cálido, popular y colorido.",
    page: "bg-[radial-gradient(circle_at_top_left,#fef3c7,transparent_34%),linear-gradient(135deg,#fff7ed,#fefce8)]",
    header: "bg-gradient-to-r from-rose-700 via-orange-600 to-amber-500 text-white",
    eyebrow: "text-amber-100",
    title: "text-white",
    body: "text-orange-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-amber-300 bg-amber-50 text-slate-950",
    productCard: "border-amber-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-amber-200 bg-white text-slate-900",
    input: "border-amber-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-rose-700 text-white hover:bg-rose-600",
    secondaryBtn: "border-amber-300 bg-white text-rose-800 hover:bg-amber-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-rose-800",
    accentPill: "bg-rose-50 text-rose-800",
    customizer: "border-amber-200 bg-white",
    customizerText: "text-slate-800",
  },
  ELEGANTE: {
    label: "Elegante nocturno",
    description: "Premium, oscuro y sobrio.",
    page: "bg-[radial-gradient(circle_at_top,#3f2f12,transparent_28%),linear-gradient(135deg,#09090b,#18181b)]",
    header: "bg-zinc-950 text-white ring-1 ring-amber-300/25",
    eyebrow: "text-amber-200",
    title: "text-white",
    body: "text-zinc-200",
    socialLink: "border-amber-300/50 bg-amber-300/10 text-amber-100 hover:bg-amber-300/20",
    panel: "border-zinc-700 bg-zinc-900 text-zinc-50",
    productCard: "border-zinc-700 bg-zinc-900 text-zinc-50 shadow-sm",
    cartItem: "border-zinc-700 bg-zinc-950 text-zinc-50",
    input: "border-zinc-600 bg-zinc-950 text-zinc-50 placeholder:text-zinc-400",
    primaryBtn: "bg-amber-300 text-zinc-950 hover:bg-amber-200",
    secondaryBtn: "border-zinc-600 bg-zinc-950 text-zinc-100 hover:bg-zinc-800",
    titleText: "text-zinc-50",
    bodyText: "text-zinc-200",
    helperText: "text-zinc-300",
    priceText: "text-amber-300",
    accentPill: "bg-amber-300/15 text-amber-200",
    customizer: "border-zinc-700 bg-zinc-950",
    customizerText: "text-zinc-100",
  },
  TAQUERIA: {
    label: "Taquería viva",
    description: "Picante, rápido y callejero.",
    page: "bg-[radial-gradient(circle_at_top_right,#bef264,transparent_30%),linear-gradient(135deg,#f7fee7,#fff7ed)]",
    header: "bg-gradient-to-r from-lime-700 via-green-700 to-red-700 text-white",
    eyebrow: "text-lime-100",
    title: "text-white",
    body: "text-lime-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-lime-300 bg-lime-50 text-slate-950",
    productCard: "border-lime-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-lime-200 bg-white text-slate-900",
    input: "border-lime-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-lime-700 text-white hover:bg-lime-600",
    secondaryBtn: "border-lime-300 bg-white text-lime-900 hover:bg-lime-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-red-700",
    accentPill: "bg-red-50 text-red-800",
    customizer: "border-lime-200 bg-white",
    customizerText: "text-slate-800",
  },
  MARISQUERIA: {
    label: "Marisquería fresca",
    description: "Mar, frescura y playa.",
    page: "bg-[radial-gradient(circle_at_top_left,#a5f3fc,transparent_32%),linear-gradient(135deg,#ecfeff,#f0fdfa)]",
    header: "bg-gradient-to-r from-cyan-800 via-sky-700 to-teal-700 text-white",
    eyebrow: "text-cyan-100",
    title: "text-white",
    body: "text-cyan-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-cyan-300 bg-cyan-50 text-slate-950",
    productCard: "border-cyan-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-cyan-200 bg-white text-slate-900",
    input: "border-cyan-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-teal-700 text-white hover:bg-teal-600",
    secondaryBtn: "border-cyan-300 bg-white text-teal-900 hover:bg-cyan-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-teal-800",
    accentPill: "bg-teal-50 text-teal-800",
    customizer: "border-cyan-200 bg-white",
    customizerText: "text-slate-800",
  },
  CAFETERIA: {
    label: "Cafetería urbana",
    description: "Cafe, pan dulce y desayunos.",
    page: "bg-[radial-gradient(circle_at_top_right,#fecdd3,transparent_30%),linear-gradient(135deg,#fff1f2,#fafaf9)]",
    header: "bg-gradient-to-r from-stone-900 via-rose-900 to-stone-800 text-white",
    eyebrow: "text-rose-100",
    title: "text-white",
    body: "text-rose-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-rose-300 bg-rose-50 text-slate-950",
    productCard: "border-rose-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-rose-200 bg-white text-slate-900",
    input: "border-rose-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-rose-800 text-white hover:bg-rose-700",
    secondaryBtn: "border-rose-300 bg-white text-rose-900 hover:bg-rose-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-rose-800",
    accentPill: "bg-rose-50 text-rose-800",
    customizer: "border-rose-200 bg-white",
    customizerText: "text-slate-800",
  },
  PIZZERIA: {
    label: "Pizzería familiar",
    description: "Casual, roja y antojable.",
    page: "bg-[radial-gradient(circle_at_top_left,#fecaca,transparent_30%),linear-gradient(135deg,#fff7ed,#f0fdf4)]",
    header: "bg-gradient-to-r from-red-700 via-orange-700 to-green-700 text-white",
    eyebrow: "text-orange-100",
    title: "text-white",
    body: "text-orange-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-red-300 bg-red-50 text-slate-950",
    productCard: "border-red-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-red-200 bg-white text-slate-900",
    input: "border-red-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-red-700 text-white hover:bg-red-600",
    secondaryBtn: "border-red-300 bg-white text-red-900 hover:bg-red-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-green-800",
    accentPill: "bg-green-50 text-green-800",
    customizer: "border-red-200 bg-white",
    customizerText: "text-slate-800",
  },
  SUSHI: {
    label: "Sushi neon",
    description: "Moderno, limpio y nocturno.",
    page: "bg-[radial-gradient(circle_at_top_right,#67e8f9,transparent_24%),linear-gradient(135deg,#020617,#0f172a)]",
    header: "bg-slate-950 text-white ring-1 ring-cyan-300/30",
    eyebrow: "text-cyan-200",
    title: "text-white",
    body: "text-slate-200",
    socialLink: "border-cyan-300/50 bg-cyan-300/10 text-cyan-100 hover:bg-cyan-300/20",
    panel: "border-cyan-400/40 bg-slate-950 text-slate-50",
    productCard: "border-cyan-400/30 bg-slate-900 text-slate-50 shadow-sm",
    cartItem: "border-cyan-400/25 bg-slate-950 text-slate-50",
    input: "border-cyan-400/40 bg-slate-950 text-slate-50 placeholder:text-slate-400",
    primaryBtn: "bg-cyan-300 text-slate-950 hover:bg-cyan-200",
    secondaryBtn: "border-cyan-400/40 bg-slate-950 text-cyan-100 hover:bg-slate-900",
    titleText: "text-slate-50",
    bodyText: "text-slate-200",
    helperText: "text-cyan-100",
    priceText: "text-cyan-300",
    accentPill: "bg-cyan-300/15 text-cyan-100",
    customizer: "border-cyan-400/30 bg-slate-950",
    customizerText: "text-slate-100",
  },
  HAMBURGUESAS: {
    label: "Hamburguesas street",
    description: "Urbano, amarillo y potente.",
    page: "bg-[radial-gradient(circle_at_top_left,#fde047,transparent_28%),linear-gradient(135deg,#18181b,#3f1d0b)]",
    header: "bg-gradient-to-r from-zinc-950 via-orange-950 to-yellow-700 text-white",
    eyebrow: "text-yellow-200",
    title: "text-white",
    body: "text-yellow-50",
    socialLink: "border-yellow-300/60 bg-yellow-300/10 text-yellow-100 hover:bg-yellow-300/20",
    panel: "border-yellow-400/50 bg-zinc-950 text-zinc-50",
    productCard: "border-yellow-400/40 bg-zinc-900 text-zinc-50 shadow-sm",
    cartItem: "border-yellow-400/30 bg-zinc-950 text-zinc-50",
    input: "border-yellow-400/50 bg-zinc-950 text-zinc-50 placeholder:text-zinc-400",
    primaryBtn: "bg-yellow-300 text-zinc-950 hover:bg-yellow-200",
    secondaryBtn: "border-yellow-400/50 bg-zinc-950 text-yellow-100 hover:bg-zinc-900",
    titleText: "text-zinc-50",
    bodyText: "text-zinc-200",
    helperText: "text-yellow-100",
    priceText: "text-yellow-300",
    accentPill: "bg-yellow-300/15 text-yellow-100",
    customizer: "border-yellow-400/30 bg-zinc-950",
    customizerText: "text-zinc-100",
  },
  ANTOJITOS: {
    label: "Antojitos coloridos",
    description: "Familiar, alegre y tradicional.",
    page: "bg-[radial-gradient(circle_at_top_right,#f9a8d4,transparent_26%),linear-gradient(135deg,#fff7ed,#fdf2f8)]",
    header: "bg-gradient-to-r from-fuchsia-700 via-rose-700 to-orange-600 text-white",
    eyebrow: "text-pink-100",
    title: "text-white",
    body: "text-orange-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-fuchsia-300 bg-fuchsia-50 text-slate-950",
    productCard: "border-fuchsia-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-fuchsia-200 bg-white text-slate-900",
    input: "border-fuchsia-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-fuchsia-700 text-white hover:bg-fuchsia-600",
    secondaryBtn: "border-fuchsia-300 bg-white text-fuchsia-900 hover:bg-fuchsia-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-fuchsia-800",
    accentPill: "bg-orange-50 text-orange-800",
    customizer: "border-fuchsia-200 bg-white",
    customizerText: "text-slate-800",
  },
  BAR_BOTANERO: {
    label: "Bar botanero",
    description: "Noche, botanitas y bebidas.",
    page: "bg-[radial-gradient(circle_at_top,#a78bfa,transparent_25%),linear-gradient(135deg,#111827,#1f2937)]",
    header: "bg-gradient-to-r from-gray-950 via-purple-950 to-amber-900 text-white",
    eyebrow: "text-amber-200",
    title: "text-white",
    body: "text-gray-100",
    socialLink: "border-amber-300/50 bg-amber-300/10 text-amber-100 hover:bg-amber-300/20",
    panel: "border-purple-400/35 bg-gray-950 text-gray-50",
    productCard: "border-purple-400/30 bg-gray-900 text-gray-50 shadow-sm",
    cartItem: "border-purple-400/25 bg-gray-950 text-gray-50",
    input: "border-purple-400/40 bg-gray-950 text-gray-50 placeholder:text-gray-400",
    primaryBtn: "bg-amber-300 text-gray-950 hover:bg-amber-200",
    secondaryBtn: "border-purple-400/40 bg-gray-950 text-purple-100 hover:bg-gray-900",
    titleText: "text-gray-50",
    bodyText: "text-gray-200",
    helperText: "text-purple-100",
    priceText: "text-amber-300",
    accentPill: "bg-amber-300/15 text-amber-100",
    customizer: "border-purple-400/30 bg-gray-950",
    customizerText: "text-gray-100",
  },
  DARK_KITCHEN: {
    label: "Dark kitchen",
    description: "Delivery moderno y directo.",
    page: "bg-[radial-gradient(circle_at_top_left,#fb7185,transparent_24%),linear-gradient(135deg,#020617,#111827)]",
    header: "bg-slate-950 text-white ring-1 ring-rose-400/30",
    eyebrow: "text-rose-200",
    title: "text-white",
    body: "text-slate-200",
    socialLink: "border-rose-300/50 bg-rose-300/10 text-rose-100 hover:bg-rose-300/20",
    panel: "border-rose-400/35 bg-slate-950 text-slate-50",
    productCard: "border-rose-400/30 bg-slate-900 text-slate-50 shadow-sm",
    cartItem: "border-rose-400/25 bg-slate-950 text-slate-50",
    input: "border-rose-400/40 bg-slate-950 text-slate-50 placeholder:text-slate-400",
    primaryBtn: "bg-rose-400 text-slate-950 hover:bg-rose-300",
    secondaryBtn: "border-rose-400/40 bg-slate-950 text-rose-100 hover:bg-slate-900",
    titleText: "text-slate-50",
    bodyText: "text-slate-200",
    helperText: "text-rose-100",
    priceText: "text-rose-300",
    accentPill: "bg-rose-300/15 text-rose-100",
    customizer: "border-rose-400/30 bg-slate-950",
    customizerText: "text-slate-100",
  },
  POLLERIA: {
    label: "Pollería rostizada",
    description: "Cálido, familiar y de comida corrida.",
    page: "bg-[radial-gradient(circle_at_top_right,#fdba74,transparent_30%),linear-gradient(135deg,#fff7ed,#fef3c7)]",
    header: "bg-gradient-to-r from-orange-800 via-amber-700 to-yellow-600 text-white",
    eyebrow: "text-yellow-100",
    title: "text-white",
    body: "text-orange-50",
    socialLink: "border-white/50 bg-white/15 text-white hover:bg-white/25",
    panel: "border-orange-300 bg-orange-50 text-slate-950",
    productCard: "border-orange-300 bg-white text-slate-950 shadow-sm",
    cartItem: "border-orange-200 bg-white text-slate-900",
    input: "border-orange-300 bg-white text-slate-950 placeholder:text-slate-500",
    primaryBtn: "bg-orange-700 text-white hover:bg-orange-600",
    secondaryBtn: "border-orange-300 bg-white text-orange-900 hover:bg-orange-50",
    titleText: "text-slate-950",
    bodyText: "text-slate-700",
    helperText: "text-slate-600",
    priceText: "text-orange-800",
    accentPill: "bg-yellow-50 text-yellow-800",
    customizer: "border-orange-200 bg-white",
    customizerText: "text-slate-800",
  },
};

export const publicThemeOptions = Object.entries(publicThemes).map(([value, theme]) => ({
  value: value as PublicThemeKey,
  label: theme.label,
  description: theme.description,
}));

export function getPublicTheme(value: string | null | undefined) {
  return publicThemes[(value as PublicThemeKey) ?? "CLASICO"] ?? publicThemes.CLASICO;
}
